Feat: Above-the-fold changes
estuary/marketing-site pull request #155
Opened 2023-11-15 18:56 UTC by flavioriper

### **Description**
We need this to change the Tagline texts, change the secondary CTA to open a hubspot form dialog and the inclusion of a bar at the top of the page for an interactive tour.

2023-11-15 19:41 UTC, jshearer requested changes
Looks great other than the 1 typo that I could see. Loving the `showTour` flag to `<Layout>` and new `<HubspotModal/>` component 😍

2023-11-15 19:41 UTC, jshearer commented on src/components/SectionOne.tsx
> +                    <h1>Real-time ETL & DCD</h1>
`DCD` -> `CDC`

2023-11-15 19:46 UTC, flavioriper commented on src/components/SectionOne.tsx
> +                    <h1>Real-time ETL & DCD</h1>
Thanks, fixed

2023-11-16 14:04 UTC, jshearer approved these changes
LGTM thank you!

2023-11-16 14:05 UTC, merged