Feat: add Osano MGMT
estuary/marketing-site pull request #179
Opened 2023-12-21 21:29 UTC by flavioriper

https://cmp.osano.com/16CPXbTOi1sXx4D3/1e6b223c-ed10-4c4b-a442-48fea69f76af/osano.js

2023-12-22 16:14 UTC, travjenkins commented
Great - this follows the approach called out in the [Osano docs](https://docs.osano.com/installing-osano-gatsby). 

Depending on needs we might want to move this script up in the future. It _should_ load before any other ones.
![image](https://github.com/estuary/marketing-site/assets/270078/f36a7fd7-a17b-4f95-8eb2-12f07009e431)

But I checked two other popular brand sites I know use Osano and they are loading exactly as we are so I think we are fine.

2024-01-03 15:14 UTC, jshearer reviewed
I'm going to hold off on approving this until @dyaffe says go for it, since it also adds Hotjar again. We've added and removed hotjar in the past because it hurts our google pagespeed numbers when we add it, so I don't want to go back and forth again. If you throw up a PR that _just_ adds Osano I'll approve it now 👍

2024-01-12 13:48 UTC, travjenkins commented
I should add that including Osano will more than likely make an impact on performance. Google will more than likely see it as a blocking scripts that makes other scripts wait on it for loading. However, this is literally the feature that Osano provides so I am not really sure how much can be done about that.

Wanting to call this out now so no one is surprised. Also, if Osano is already going to make a potential impact it might be easier to push the addition of HotJat in a stand alone PR to make figuring out performance stuff easier.

2024-01-12 17:09 UTC, dyaffe commented
Why are we adding Hotjar?  As Joseph mentioned, I'm pretty anxious about adding that in due to page speed issues with Google SEO metrics.

2024-01-15 10:17 UTC, flavioriper commented
Removed the hotjar until we figure out a better solution to it

2024-01-19 01:08 UTC, travjenkins commented
When are we planning to merge this?

2024-01-19 17:07 UTC, jshearer requested changes

2024-01-19 17:07 UTC, jshearer commented on gatsby-config.ts
> +        {
Ok I heard back from @dyaffe: can we remove this `vwo` stuff for now please? Once that's done this is good to go

2024-01-19 17:14 UTC, flavioriper commented on gatsby-config.ts
> +        {
vwo removed

2024-01-19 17:16 UTC, jshearer requested changes

2024-01-19 17:16 UTC, jshearer commented on gatsby-config.ts
> +            resolve: "gatsby-plugin-vwo-smartcode",
This still needs to be removed, build will fail otherwise

2024-01-19 19:31 UTC, jshearer approved these changes
LGTM

2024-01-19 19:31 UTC, merged