Fix: GA cors error
estuary/marketing-site pull request #216
Opened 2024-03-11 19:38 UTC by flavioriper

## Changes

-   Changed the GA script to be pulled on each build to being hosted locally. This will fix the GA cors issue.

## Tests / Screenshots

![image](https://github.com/estuary/marketing-site/assets/40703179/5a74d797-0b68-4c07-9379-4fb7a59256d9)

## Lighthouse

![image](https://github.com/estuary/marketing-site/assets/270078/94136e5e-7318-45a5-b363-7ede6fc9cd59)

2024-03-12 14:27 UTC, travjenkins commented on static/gtag.js
We should not just be inline-ing this script like this. If we want to solve this problem this way we need to fetch the tag during build so it stays up to date.

Also - we need to get an idea of how often this changes as this could end up meaning we use an old version of this file and cause other issues.

2024-03-12 14:28 UTC, travjenkins commented on gatsby-config.ts
> +    partytownProxiedURLs: [`https://www.googletagmanager.com/gtag/js?id=G-P1PZPE4HHZ`],
We are we setting up a proxied url here? 

Also - we should make `GA_MEASUREMENT_ID` be reusable everywhere in the app so we are not hardcoding it in one spot and not in others. If that is too tough then it needs commented and called out this is hardcoded and needs to stay in sync.

2024-03-12 14:30 UTC, travjenkins commented
One issue with Partytown and GA is this break the testing tool : https://github.com/BuilderIO/partytown/issues/72

We should probably look into that a bit to see if there are any solutions/ideas/work arounds in that issue

2024-03-12 14:55 UTC, flavioriper commented on gatsby-config.ts
> +    partytownProxiedURLs: [`https://www.googletagmanager.com/gtag/js?id=G-P1PZPE4HHZ`],
I will remove this proxy, I was trying to find a solution without hosting the script ourselves.

2024-03-13 15:17 UTC, travjenkins commented on gatsby-node.ts
> +    await writeFile(path.join(__dirname, 'static', 'analytics.js'), buffer);
This needs very basic error handling.

As a fast follow we need to include a `sha` to compare against so we know when this changes / we got the right file.

2024-03-13 15:19 UTC, flavioriper commented
> One issue with Partytown and GA is this break the testing tool : [BuilderIO/partytown#72](https://github.com/BuilderIO/partytown/issues/72)
> 
> We should probably look into that a bit to see if there are any solutions/ideas/work arounds in that issue

Since our GA script is completely down we can't check if it's happening to us, so I would suggest moving on to fix the problem we have now.

what do you think?

2024-03-13 15:22 UTC, travjenkins commented on gatsby-node.ts
> +    const response = await fetch('https://google-analytics.com/analytics.js');
Current: `https://www.googletagmanager.com/gtag/js?id=G-P1PZPE4HHZ`
New: `https://google-analytics.com/analytics.js`

These two files are not the same thing. What is driving us to no longer load tag manager? That can include more than just analytics.

2024-03-13 15:23 UTC, travjenkins requested changes
Some call outs and required changes

2024-03-13 15:50 UTC, travjenkins commented
> > One issue with Partytown and GA is this break the testing tool : [BuilderIO/partytown#72](https://github.com/BuilderIO/partytown/issues/72)
> > We should probably look into that a bit to see if there are any solutions/ideas/work arounds in that issue
> 
> Since our GA script is completely down we can't check if it's happening to us, so I would suggest moving on to fix the problem we have now.
> 
> what do you think?

This tool is to be used locally.... I do not think this is impacted by the prod issue.

2024-03-13 15:51 UTC, flavioriper commented on static/gtag.js
Since the GA script is not something that changes that much (it barely changes tbh), I say we could inline it for now, at least to solve our priority which is the GA missing metrics. 

To change for something that fetches the tag during build would require a lot of effort and tests

2024-03-13 16:43 UTC, flavioriper commented
> > > One issue with Partytown and GA is this break the testing tool : [BuilderIO/partytown#72](https://github.com/BuilderIO/partytown/issues/72)
> > > We should probably look into that a bit to see if there are any solutions/ideas/work arounds in that issue
> > 
> > 
> > Since our GA script is completely down we can't check if it's happening to us, so I would suggest moving on to fix the problem we have now.
> > what do you think?
> 
> This tool is to be used locally.... I do not think this is impacted by the prod issue.

![image](https://github.com/estuary/marketing-site/assets/40703179/18cf7c72-ea42-430c-850f-63affd5fa80e)

it's connecting here, so we probably fine

2024-03-13 16:49 UTC, flavioriper commented
Moved GA to be hosted statically within the project like before since it's something that barely changes over the year.

2024-03-13 17:17 UTC, travjenkins approved these changes
lgtm

We'll need some stuff built out to make this a proper solution as a fast follow.

Do not merge until a full build/test deploy is double checked.

2024-03-13 17:43 UTC, flavioriper commented
The build/test deployment is completed and healthy

can we go for the merge? @travjenkins

2024-03-13 18:56 UTC, merged