Brenosalv/feature/implement-a-max-width-for-the-site
estuary/marketing-site pull request #284
Opened 2024-05-04 03:53 UTC by Brenosalv

This PR solves issue #255.

2024-05-09 06:05 UTC, Brenosalv commented
Just correcting: The commit [7dd6061](https://github.com/estuary/marketing-site/pull/284/commits/7dd606150b73ea03c353343fca0e2cdb559f8a38) was for the connector template, not blog post template.

2024-05-09 16:11 UTC, travjenkins commented
Integration pages with source and destination selected are too wide

![image](https://github.com/estuary/marketing-site/assets/270078/1baf8b14-cfe2-4cc6-809c-1ac617f62765)

2024-05-09 16:18 UTC, travjenkins commented
The `404` page does not follow the width
![image](https://github.com/estuary/marketing-site/assets/270078/1e80000b-dd8c-478a-9193-b77e3b156797)

2024-05-09 16:31 UTC, travjenkins requested changes
need a few small fixes

2024-05-09 20:32 UTC, travjenkins commented on src/pages/404.tsx
> +`;
You have two `Container`s

![image](https://github.com/estuary/marketing-site/assets/270078/23876e72-c33f-4d26-b2e0-9ad06f76316a)

2024-05-09 20:34 UTC, Brenosalv commented on src/pages/404.tsx
> +`;
Fixed.

2024-05-09 21:00 UTC, travjenkins submitted a review, later dismissed
lgtm - would like to wait for another preview build to complete for one last quick look before merging.

2024-05-09 22:03 UTC, travjenkins commented
When selecting source and destination the images can quickly get way too small. I think we need to make sure that "column" does not shrink down too much with the new width
![image](https://github.com/estuary/marketing-site/assets/270078/e95b2484-a7cb-4684-b064-5701f6c3b76b)

2024-05-09 22:06 UTC, travjenkins commented
https://estuary-marketing--pr284-brenosalv-feature-im-qjveud3g.web.app/integrations/datadog-ingest-to-google-cloud-sql-sqlserver/

You need to use ones with longer names to see the issue

2024-05-09 22:07 UTC, travjenkins commented
If we turn off `nowrap` on the text I think it looks okay - 
![image](https://github.com/estuary/marketing-site/assets/270078/feb6832b-4000-4d2f-b3da-185b8b93521b)

2024-05-09 22:28 UTC, Brenosalv commented
> If we turn off `nowrap` on the text I think it looks okay - ![image](https://private-user-images.githubusercontent.com/270078/329400743-feb6832b-4000-4d2f-b3da-185b8b93521b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyOTI3NTEsIm5iZiI6MTcxNTI5MjQ1MSwicGF0aCI6Ii8yNzAwNzgvMzI5NDAwNzQzLWZlYjY4MzJiLTQwMDAtNGQyZi1iM2RhLTE4NWI4YjkzNTIxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQyMjA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWE4MGQ3MGE4MjJhNWY5NDVlYjg5OWM1YjgxYmU4ZWY5NThhNDgwMThiYmJkYjE4MzZhMmNmNzE5NTg2N2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CZ_OaEXYjN85Y0BuLJfhn_eWBds-sDCyGMIAjAnArGU)

Thanks, Travis, that's exactly the solution.

2024-05-10 00:14 UTC, travjenkins commented
Sorry - found one more while testing on my home machine.
<img width="1053" alt="image" src="https://github.com/estuary/marketing-site/assets/270078/88eec623-e8bd-4caa-836c-d8b8cd952e84">

We should mark these connector icons with hardcoded width and height? However, that can cause the chips to overflow
<img width="1053" alt="image" src="https://github.com/estuary/marketing-site/assets/270078/71f83e33-3840-4111-ba75-bd72c2c0f5f7">

If we allow the flex items to `wrap` and align them to the `end` it looks okay
<img width="536" alt="image" src="https://github.com/estuary/marketing-site/assets/270078/5854f7cd-198d-42d7-a44c-171ffc40e7d2">

I am not super strong about any specific solution though - just wanted to leave a basic idea of a quick solution

2024-05-10 01:49 UTC, Brenosalv commented
> Sorry - found one more while testing on my home machine. <img alt="image" width="1053" src="https://private-user-images.githubusercontent.com/270078/329418273-88eec623-e8bd-4caa-836c-d8b8cd952e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDAzNzQsIm5iZiI6MTcxNTMwMDA3NCwicGF0aCI6Ii8yNzAwNzgvMzI5NDE4MjczLTg4ZWVjNjIzLWU4YmQtNGNhYS04MzZjLWQ4YjhjZDk1MmU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMDE0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGExMDI3MjQxZTY5ZTBkNTVjN2E4NDgzZjg1NjVhOWY2NzhiNmNiZTBjMDEwNDZjZGQ1NDY0OTRlZGYwMGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0q3QWuD7ah5ok7pxvNiOuv4Vq3UFvXp8PMtxOrnOVUE">
> 
> We should mark these connector icons with hardcoded width and height? However, that can cause the chips to overflow <img alt="image" width="1053" src="https://private-user-images.githubusercontent.com/270078/329418441-71f83e33-3840-4111-ba75-bd72c2c0f5f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDAzNzQsIm5iZiI6MTcxNTMwMDA3NCwicGF0aCI6Ii8yNzAwNzgvMzI5NDE4NDQxLTcxZjgzZTMzLTM4NDAtNDExMS1iYTc1LWJkNzJjMmMwZjVmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMDE0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDdmY2Q1OGIwMzdjODljYjliOGRlNmVlODNhZWFhNjY1ODBiYmU3NDM1N2ZkYTQ0OWE5ZmQ1NTJhNGJhZTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sOHG7lWFcmKxl458hyL_ZJizqdS8851Hc0__w1Aaaz4">
> 
> If we allow the flex items to `wrap` and align them to the `end` it looks okay <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/270078/329418756-5854f7cd-198d-42d7-a44c-171ffc40e7d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDAzNzQsIm5iZiI6MTcxNTMwMDA3NCwicGF0aCI6Ii8yNzAwNzgvMzI5NDE4NzU2LTU4NTRmN2NkLTE5OGQtNDJkNy1hNDRjLTE3MWZmYzQwZTdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMDE0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmUxMWZlNjU1OWFkMzcwNWRkM2UyMzEzMDE0NTZjYjE3NzE4NGU3ZWRkYzljYjY2YjIzZDhhOWE4MTYxNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YKVHA5DObk0Rt768ol6H8WE7_aGRMwcBsfxL5kPA-So">
> 
> I am not super strong about any specific solution though - just wanted to leave a basic idea of a quick solution

I see it's an issue already present in production. I like your solution but I prefer besides adding a max-width 55px to the icons, also adjusting the grid to become 3 columns earlier. Please let me know what you think about this solution. I just pushed a new commit.

2024-05-10 14:23 UTC, travjenkins approved these changes
lgtm

2024-05-10 14:24 UTC, merged