Brenosalv/bug/help-chat-not-showing-up-sometimes
estuary/marketing-site pull request #307
Opened 2024-05-21 21:02 UTC by Brenosalv

## Changes

-   Help Chat is not showing up sometimes when reloading the pages.
-   Possible solution: remove the react hooks to avoid inconsistencies.

## Tests / Screenshots

-   Help Chat: 
![image](https://github.com/estuary/marketing-site/assets/60396753/80e351d8-3b40-44ef-bab8-85aa5ceef3ab)

-  React in the gatsby-browser.tsx
![image](https://github.com/estuary/marketing-site/assets/60396753/51495626-ce77-494d-82ff-820a555b8dfe)

2024-05-22 01:06 UTC, Brenosalv commented
Desktop:
![image](https://github.com/estuary/marketing-site/assets/60396753/790951ce-c86a-48b5-b6eb-2bb8b46971bd)

Mobile:
![image](https://github.com/estuary/marketing-site/assets/60396753/53f13326-19c0-43ea-9f51-75fb3da13713)

2024-05-24 05:11 UTC, Brenosalv commented
Desktop report with the help chat placeholder:
![image](https://github.com/estuary/marketing-site/assets/60396753/eff2e54a-6ae9-4000-9c49-6d9f426b0381)

2024-05-24 13:05 UTC, travjenkins commented on gatsby-browser.tsx
> +      )}
This is not the solution I'd recommend. I am thinking this should be handled more like how this plugin can load in HubSpot. It does not need to be done exactly like this - but should be loaded from within the component itself.

https://github.com/escaladesports/react-hubspot-form/blob/d439bb88631eb8864e96397a0d4c23e81cf1929f/src/index.js#L44

2024-05-24 14:23 UTC, travjenkins commented
So comparing the live analysis from Google and dynamic loading did not make an impact. Let's go ahead and put it back to how it was loading and just go with the new React component approach you made to solve the state issues.

2024-05-24 14:23 UTC, travjenkins requested changes
Do not need to load dynamically

2024-05-24 15:12 UTC, Brenosalv commented
@travjenkins I wouldn't consider adding states here since it could cause unnecessary rerenders. Intead we just need to check the screen width and height on the first render and load it or not. Don't you aggree?

2024-05-24 15:45 UTC, Brenosalv commented
@travjenkins I think we don't need the component because we don't need the state. We just need to check if the screen width or height is less than 768px on load/first render and we can do it without states. Please let me know if you aggree.

2024-05-28 13:02 UTC, merged