Brenosalv/feature/updated-menu-design
estuary/marketing-site pull request #335
Opened 2024-05-31 06:00 UTC by Brenosalv

#324 

## Changes

- [ ] Add redesigned product menu;
- [ ] Add redesigned resources menu

## Tests / Screenshots

-   ![image](https://github.com/estuary/marketing-site/assets/60396753/eab3b6da-54e7-4f5c-a64c-ca0b145d7d04)
-   ![image](https://github.com/estuary/marketing-site/assets/60396753/f3699b45-b147-4490-863e-7a1f7414fc4e)

2024-05-31 13:31 UTC, Brenosalv commented on package.json
> +    "fix": "yarn lint:fix && yarn format:fix",
@travjenkins I added this script to make fixing things easier before committing, since we don't have the fix in husky.

2024-05-31 13:48 UTC, travjenkins commented on package.json
> +    "fix": "yarn lint:fix && yarn format:fix",
Makes sense

2024-05-31 17:09 UTC, travjenkins commented on src/components/HeaderNavbar/CardItem/styles.ts
> +    color: #ffffff;
Could we move the color into a parent to reduce duplication. I know this is a tiny thing but trying to keep CSS as small as possible.

2024-05-31 17:11 UTC, travjenkins commented on src/components/HeaderNavbar/Resources/index.tsx
> +                            href={webinarsUrl} // TODO: replace this URL with the tour video URL
FYI - a `todo` is still in here.

2024-05-31 17:15 UTC, travjenkins commented on src/globalStyles.ts
> +            return lightStyles;
I think we're fine just having `light` be the default and not checked up above. That way we don't need to store off the lightStyles. 

Also, can we make the border styling shared?

2024-05-31 17:15 UTC, travjenkins commented on src/images/product-tour-2min.png
What changed with this?

2024-05-31 18:09 UTC, Brenosalv commented on src/images/product-tour-2min.png
I replaced the image with a bigger one.

2024-05-31 18:53 UTC, travjenkins commented on src/images/product-tour-2min.png
Cool - asking cause I was thinking "I have seen this exact image before" lol

2024-05-31 18:53 UTC, travjenkins requested changes
a few small changes

2024-06-04 12:36 UTC, travjenkins commented on src/components/HeaderNavbar/Card/styles.ts
> +    background-color: #00000099;
This looks wrong... there are more than 6 digits. Does hex support opacity with the last two digits?

2024-06-04 12:38 UTC, travjenkins commented on src/components/header.tsx
> +                            title="Menu"
Can we update this to `Navigation Menu` to be more specific.

2024-06-04 14:07 UTC, Brenosalv commented on src/components/header.tsx
> +                            title="Menu"
Sure, makes sense.

2024-06-04 14:13 UTC, Brenosalv commented on src/globalStyles.ts
> +            return lightStyles;
Makes sense. Will do this.

2024-06-04 14:13 UTC, Brenosalv commented on src/components/HeaderNavbar/Resources/index.tsx
> +                            href={webinarsUrl} // TODO: replace this URL with the tour video URL
Yeah, I was keeping it to remove when working on the carousel.

2024-06-04 14:21 UTC, Brenosalv commented on src/components/HeaderNavbar/CardItem/styles.ts
> +    color: #ffffff;
I can do this but it's a problem that is present in all the css codes. We could create an issue to store all the colors of the entire application in a file as ```globalStylies.ts``` and import from there.

2024-06-04 14:32 UTC, travjenkins commented on src/components/HeaderNavbar/CardItem/styles.ts
> +    color: #ffffff;
I would like to reduce how much we're importing and reapplying styles if we can. I would like to style a lot of stuff at the top level and then only use styling to override when needed.

2024-06-04 14:32 UTC, travjenkins commented on src/components/HeaderNavbar/CardItem/styles.ts
> +    color: #ffffff;
And yeah - this is a big problem in the app for sure... this is not coming from the code of just this PR :D

2024-06-04 17:20 UTC, travjenkins commented on src/components/HeaderNavbar/Resources/items.tsx
> +            <StaticImage src="../../../svgs/microphone.svg" alt="About us" />
Can we try to get some better `alt` text in here?

2024-06-04 17:20 UTC, travjenkins commented on src/components/HeaderNavbar/Resources/items.tsx
> +            <StaticImage src="../../../svgs/microphone.svg" alt="About us" />
Same applies to the two images down below.

2024-06-04 17:27 UTC, Brenosalv commented on src/components/HeaderNavbar/Resources/items.tsx
> +            <StaticImage src="../../../svgs/microphone.svg" alt="About us" />
Okay, I will follow the same idea of the About us from the image up above. This way the alt text would be "Podcasts", "Webinars" and "Youtube".

2024-06-04 18:11 UTC, Brenosalv commented on src/components/Carousel/index.tsx
> +        if (hasMounted.current && slideRefs.current[currentSlide]) {
@travjenkins The scrolling problem here was caused by the ```scrollIntoView()``` being called on first render. Now we are preventing the component to call it initially using a ref.

2024-06-04 18:13 UTC, Brenosalv commented
@travjenkins Also, I removed the ```keen-slider``` package and replaced the connectors page carousel with the new one allowing the same colors to the dots.

2024-06-05 00:19 UTC, Brenosalv commented on src/components/Carousel/styles.ts
> +    align-items: center;
https://github.com/estuary/marketing-site/issues/314https://github.com/estuary/marketing-site/issues/314

I resolved the issue by centering the slide content. I believe this is the maximum reduction we can achieve for the spacing between the testimonials and dots from the carousel.

2024-06-06 12:42 UTC, travjenkins commented on src/components/Carousel/styles.ts
> +    align-items: center;
I think this is okay for now. It is better than before in my opinion. Probably see what Lucas thinks.

Eventually we should put some effort into adjusting the height dynamically.

2024-06-06 12:47 UTC, travjenkins commented on src/components/HeaderNavbar/Card/index.tsx
> +    }
What is driving the need of this? Are we not able to style `MenuBackground` for small screens with just css?

2024-06-06 13:56 UTC, Brenosalv commented
@travjenkins As we don't have a mobile version of the redesigned menus, I felt free to develop the responsiveness including an accordion when it's in mobile devices. Also, the mobile version in prod is bugged when clicking on the header links "Product" and "Resources" requiring us sometimes double clicking to open them. Please let me know your thoughts.

2024-06-06 14:29 UTC, Brenosalv commented on src/components/HeaderNavbar/Card/index.tsx
> +    }
You're totally right, there is no need of this. Changed to css only.

2024-06-06 14:52 UTC, Brenosalv commented on src/components/Carousel/styles.ts
> +    align-items: center;
I thought about adjusting the height dinamically but I personally didn't like the UX like that.

I talked to Lucas and had a positive feedback about the spacing.

Also, I adjusted the homepage testimonials' logo and font sizes according to figma design. They were too big for mobile.

2024-06-06 15:26 UTC, travjenkins commented
Only major feedback on mobile menu is I think the items should be spaced vertically a bit more

Current
![image](https://github.com/estuary/marketing-site/assets/270078/e89d30d5-4d32-49d0-bad4-b6a7de29ce79)

Increasing `gap` to `12px`
![image](https://github.com/estuary/marketing-site/assets/270078/2c563ff8-be83-48b0-ab21-f4db0a6c6291)

2024-06-06 17:58 UTC, travjenkins submitted a review, later dismissed
lgtm

2024-06-07 12:45 UTC, travjenkins submitted a review, later dismissed
lgtm

2024-06-07 18:51 UTC, travjenkins submitted a review, later dismissed
lgtm - this **really** makes the nav look better.

2024-06-08 00:58 UTC, travjenkins approved these changes
lgtm - hit the preview app and looked around and looked at the changes in the styling (post merge)

2024-06-10 14:16 UTC, merged