Add comparison pages
estuary/marketing-site pull request #503
Opened 2024-09-23 19:00 UTC by Brenosalv

#457 

## Changes

-   Create comparison center page;
-   Create comparison XvsY page.

2024-10-03 21:33 UTC, Brenosalv commented on src/pages/etl-tools/index.tsx
> +        }
Fetching only the estuary id seems redundant but if the id changes in strapi, we'll know because the query won't work anymore.

We are using the estuary vendor id for setting the estuary tab as default here:
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/8efb3e2a-ebdd-4e46-b207-2f070fe44a80">

2024-10-04 20:14 UTC, travjenkins commented on .lighthouserc.js
> +                'http://localhost:9000/etl-tools/estuary-vs-fivetran/index.html',
We'll need redirects for `confluent` as well.

2024-10-07 03:06 UTC, Brenosalv commented on .lighthouserc.js
> +                'http://localhost:9000/etl-tools/estuary-vs-fivetran/index.html',
I added redirects for all the comparison links from the menu. I'm considering all of them are indexed.

2024-10-08 14:47 UTC, travjenkins commented on src/components/BlogPostToc/index.tsx
> +                                maxWidth: '36px',
Why is this styling not park of the `accordionSidePadding` styling?

2024-10-08 15:57 UTC, travjenkins commented on src/components/EtlToolsPage/SectionTwo/index.tsx
> +                    />
the `title` is the same on both of these cards... I think the comparison one needs updated.

2024-10-08 15:57 UTC, travjenkins commented on src/components/EtlToolsPage/shared.ts
Looks like an empty file - I think we can delete?

2024-10-08 15:59 UTC, travjenkins commented on src/components/EtlToolsXvsYPage/SectionThree/index.tsx
> +                                color="#5072EB"
We are using `#5072EB` in a lot of places here. Can we get that shared in a single const?

2024-10-08 16:02 UTC, travjenkins commented on src/components/EtlToolsXvsYPage/SectionTwo/Connectors/index.tsx
All these stand alone components are basically the same. We need to make a single template that they all pull from.

2024-10-08 16:15 UTC, travjenkins commented on src/pages/etl-tools/index.tsx
> +        }
Yeah... I that makes sense. That way it changing could be caught by breaking the build.

2024-10-08 16:16 UTC, travjenkins requested changes
The only major change we really need to making all the table row stuff to be shared.

2024-10-08 21:19 UTC, Brenosalv commented on src/components/EtlToolsPage/SectionTwo/index.tsx
> +                    />
Actually one is for "ELT" and other for "ETL". Don't you think it's better to keep them independent?

2024-10-08 21:26 UTC, Brenosalv commented on src/components/EtlToolsXvsYPage/SectionThree/index.tsx
> +                                color="#5072EB"
Yeah, the same for the 28. I will create two consts out of the component scope.

2024-10-08 21:39 UTC, Brenosalv commented on src/components/EtlToolsXvsYPage/index.tsx
Oh, I wasn't aware of this - thanks for the heads up.

2024-10-08 21:41 UTC, Brenosalv commented
Build failed due to Strapi changes. I will re-run the site build once the strapi build finishes.

2024-10-08 22:43 UTC, travjenkins commented on src/components/EtlToolsPage/SectionTwo/index.tsx
> +                    />
Oh I see... but still shouldn't the `title` match the `href`? 

The first linke os to a "comparison guide" so I would think the title would be "The Data Engineer's Guide to ELT Comparisons"

2024-10-08 22:49 UTC, Brenosalv commented on src/components/EtlToolsPage/SectionTwo/index.tsx
> +                    />
Oh yeah, I followed the design and didn't notice this. Thanks.

2024-10-08 22:53 UTC, Brenosalv commented on src/components/EtlToolsPage/SectionTwo/index.tsx
> +                    />
Checking the blog post title, the title really is "Alternatives":
<img width="2036" alt="image" src="https://github.com/user-attachments/assets/5e358dd9-f0fd-4096-aa8d-fbf6532324ed">

2024-10-08 23:05 UTC, Brenosalv commented on src/components/BlogPostToc/index.tsx
> +                                maxWidth: '36px',
No reason, it should be part of the class. Fixed.

2024-10-08 23:08 UTC, Brenosalv commented
A placeholder was added to the select on the right as default value:
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/d1f754e5-0d0f-42b6-ae4e-048825f702cb">

2024-10-09 15:42 UTC, travjenkins commented on src/components/EtlToolsXvsYPage/SectionTwo/TableRows/index.tsx
> +};
This is clever. We could have used a JSONPath library but this is totally fine. We will want to keep this in mind if we add more data that the names cannot contain a `.` in them.

2024-10-09 15:46 UTC, travjenkins commented on src/components/EtlToolsXvsYPage/SectionTwo/index.tsx
> +    }, []);
Instead of 'scroll` we should be using an `IntersectionObserver` that can tell us when something is "sticky".

https://davidwalsh.name/detect-sticky

2024-10-09 15:56 UTC, travjenkins commented on src/components/EtlToolsXvsYPage/SectionTwo/index.tsx
> +    }, []);
I can take care of this quickly

2024-10-09 16:15 UTC, travjenkins commented on src/components/EtlToolsXvsYPage/SectionTwo/index.tsx
> +    }, []);
Ugh... never mind... I don't wanna hold this up so we can do this later.

2024-10-09 16:25 UTC, travjenkins submitted a review, later dismissed
lgtm - just look into that last error popping up in the console

2024-10-09 17:40 UTC, Brenosalv commented on src/components/EtlToolsXvsYPage/SectionTwo/TableRows/index.tsx
> +};
Yeah, I implemented this with scalability in mind, allowing it to handle any object, regardless of the number of nested properties.

2024-10-09 18:26 UTC, travjenkins approved these changes
lgtm

2024-10-09 18:27 UTC, travjenkins approved these changes
lgtm

2024-10-09 18:35 UTC, merged